### DISCUSSION TITLE
automation/

### DISCUSSION THREAD

**Discussion by giscus** [shane0/shane0.github.io#38] [General]
# automation/

https://shane0.github.io/automation/

**Comment by shane0** [comment]
- research this & the paths and try automating slides
- not sure if it is compatible with mkdocs material
- might have to run on the gh-pages branch

```yml
name: Convert Markdown to Reveal.js HTML Slide

on:
  push:
    branches:
      - master

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker://pandoc/core:2.9 with:
        args: "--from=markdown --to=revealjs"

      - name: Upload HTML Slide to GitHub Pages
        uses: actions/upload-artifact@v2 with:
          name: output.html
          path: output.html
```
