### ISSUE TITLE
stacks

### ISSUE THREAD

**Issue by shane0** [shane0/shane0.github.io#23]
# fastapi sqlite 

```yml
version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
    volumes:
      - ./backend:/app
      - ./data:/data
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  database:
    image: "sqlite:latest"
    volumes:
      - ./data:/data
```

```sh
docker-compose up
```

This will start all three services and you should be able to access the FastAPI backend at http://localhost:8000 and the React frontend at http://localhost:3000.
