### ISSUE TITLE
pipeline examples

### ISSUE THREAD

**Issue by shane0** [shane0/shane0.github.io#5]
# skipping

- set variable on the web interface cicd vars
- set the variable in the pipeline
- set the variable from the cli if you have access to the server with the gitlab runner `$ SKIP_TESTS=true gitlab-runner run <pipeline-name>`

```yml
stages:
  - test

variables:
  SKIP_TESTS: "true"

test:
  stage: test
  script:
    - if [ "$SKIP_TESTS" != "true" ]; then behave; else echo "Skipping tests..."; fi

```

**Comment by shane0** [comment]
# bash pipeline

- run bash script and save the output to a file

```yml
stages:
  - test

test:
  stage: test
  script:
    - sh myscript.sh 2>&1 | tee output.log
  artifacts:
    paths:
      - output.log
```

**Comment by shane0** [comment]
2>&1 redirects stderr to stdout, so that both stdout and stderr are captured in the file.

**Comment by shane0** [comment]
# pipeline check if file exists

```yml
stages:
  - test

check_file_exists:
  stage: test
  script:
    - if [ ! -f /path/to/file.txt ]; then echo "File does not exist"; exit 1; fi
  allow_failure: false
```

**Comment by shane0** [comment]
# python script in pipeline


```yml
stages:
  - run_script

run_script:
  stage: run_script
  script:
    - python example.py > output.txt
```

**Comment by shane0** [comment]
use a variable to skip a pipeline

```yml
  script:
    - if [ "$SKIP_TESTS" != "true" ]; then behave; fi
 ```

**Comment by shane0** [comment]
# pipeline checks for text in a file

```yml
stages:
  - test

check_file:
  stage: test
  script:
    - if ! grep -q "regex-pattern" file.txt; then echo "Text not found"; exit 1; fi
  allow_failure: false
```

```regex
grep -q "sn-cucumber-ready" filename.txt
# check for ready anywhere in a line
grep -E ".*ready.*" /path/to/file
```

**Comment by shane0** [comment]
# grep has limited regex characters

In basic mode, grep does not support certain regex characters such as +, ?, |, (, and ) which are used for grouping, alternation, and quantification. However, these characters can be used with grep in extended mode by passing the -E or --extended-regexp option. Alternatively, egrep can be used which is equivalent to grep -E.

**Comment by shane0** [comment]
# fail if web down

`curl -I -o /dev/null -w "%{http_code}" <URL> | grep -qv '200'`

```yml
stages:
  - test

variables:
  URL: https://example.com

test:
  stage: test
  image: alpine:latest
  script:
    - response=$(curl -Is -w "%{http_code}" $URL -o /dev/null)
    - echo "Response code: $response"
    - |
      if [ "$response" != "200" ]; then
        echo "Failed: Response code was $response"
        exit 1
      fi
  only:
    - master

```

**Comment by shane0** [comment]
# fail on status with more variables

```yml
stages:
  - test

variables:
  URL: "https://www.example.com"
  STATUS_CODE: "200"
  RESPONSE_MSG: "Example Domain"

test_website:
  stage: test
  image: curlimages/curl:latest
  script:
    - RESPONSE=$(curl -s -o /dev/null -w "%{http_code} %{response_message}" $URL)
    - if [[ "$RESPONSE" =~ ^$STATUS_CODE\ $RESPONSE_MSG ]]; then echo "$RESPONSE_MSG found"; else echo "$RESPONSE_MSG not found"; exit 1; fi
```

**Comment by shane0** [comment]
# content on web

```yml
stages:
  - test

variables:
  URL: "https://www.example.com"
  REGEX_PATTERN: "Hello, (.*)!"

test:
  image: python:3.9-alpine
  stage: test
  script:
    - apk add --no-cache curl jq
    - RESPONSE=$(curl -sSL ${URL})
    - RESULT=$(echo ${RESPONSE} | jq -r '.')
    - TABLE=$(echo ${RESULT} | grep -Po '<table[^>]*>[\s\S]*?</table>')
    - echo ${TABLE}
    - MATCH=$(echo ${TABLE} | grep -Po ${REGEX_PATTERN})
    - echo "Match found: ${MATCH}"
    - if [[ -z "${MATCH}" ]]; then echo "Match not found!"; exit 1; fi
  tags:
    - docker
```

**Comment by shane0** [comment]
# variables

```yml
stages:
  - create_file

variables:
  REPO_NAME: my-repo
  BRANCH_NAME: $CI_COMMIT_REF_NAME
  COMMIT_HASH: $CI_COMMIT_SHORT_SHA
  DATE: $(date -I)

create_file:
  image: alpine
  script:
    - echo "# Repository: ${REPO_NAME}\n" >> ${REPO_NAME}_${BRANCH_NAME}_${COMMIT_HASH}_${DATE}.md
    - echo "## Branch: ${BRANCH_NAME}\n" >> ${REPO_NAME}_${BRANCH_NAME}_${COMMIT_HASH}_${DATE}.md
    - echo "## Commit: ${COMMIT_HASH}\n" >> ${REPO_NAME}_${BRANCH_NAME}_${COMMIT_HASH}_${DATE}.md
    - echo "## Date: ${DATE}\n" >> ${REPO_NAME}_${BRANCH_NAME}_${COMMIT_HASH}_${DATE}.md
  artifacts:
    paths:
      - ${REPO_NAME}_${BRANCH_NAME}_${COMMIT_HASH}_${DATE}.md
```

**Comment by shane0** [comment]
# markdown lint

- badges 
- 
![lint](https://github.com/shane0/shane0.github.io/actions/workflows/markdownlint.yml/badge.svg)
![tests](https://github.com/shane0/shane0.github.io/actions/workflows/run-tests.yml/badge.svg)

```markdown
![lint](https://github.com/shane0/shane0.github.io/actions/workflows/markdownlint.yml/badge.svg)
![tests](https://github.com/shane0/shane0.github.io/actions/workflows/run-tests.yml/badge.svg)
```

```yml
stages:
  - build

markdownlint:
  image: node:latest
  script:
    - markdownlint "**/*.md"
```

> or 

```py
import subprocess

# Run markdownlint on all markdown files in the directory and its subdirectories
cmd = ['markdownlint', '-r', 'markdownlint-config.yml', '**/*.md']
result = subprocess.run(cmd, capture_output=True, text=True)

# Print the output of the command
print(result.stdout)

# Raise an error if the command exits with a non-zero status code
if result.returncode != 0:
    raise RuntimeError('Markdownlint found issues with the Markdown files.')
```

```yml
stages:
  - lint

lint_markdown:
  image: python:3.9
  script:
    - pip install markdownlint-cli
    - python markdown_lint.py
  artifacts:
    reports:
      markdownlint: markdownlint-report.json
```

**Comment by shane0** [comment]
# markdownlint-config.yml

```yml
---
# MD013: Line length
line_length:
  code_blocks: false
  tables: true
  headings: false
  front_matter: true

# MD024: Multiple headers with the same content
no_duplicate_heading: true

# MD032: Lists should be surrounded by blank lines
blanks_around_lists:
  style: "consistent"

# MD034: Bare URLs
no_bare_urls:
  allowlist:
    - "github.com"

# MD036: Emphasis used instead of a header
no_emphasis_as_header: true
```

**Comment by shane0** [comment]
```yml
default:
  MD001: true
  MD002: true
  MD003: true
  MD004: true
  MD005: true
  MD006: true
  MD007: true
  MD009: true
  MD010: true
  MD011: true
  MD012: true
  MD013: true
  MD014: true
  MD018: true
  MD019: true
  MD020: true
  MD021: true
  MD022: true
  MD023: true
  MD024: true
  MD025: true
  MD026: true
  MD027: true
  MD028: true
  MD029: true
  MD030: true
  MD031: true
  MD032: true
  MD033: true
  MD034: true
  MD035: true
  MD036: true
  MD037: true
  MD038: true
  MD039: true
  MD040: true
  MD041: true
```

**Comment by shane0** [comment]
```yml
stages:
  - test

lint:
  stage: test
  image: python:3

  before_script:
    - pip install markdownlint-cli
  script:
    - markdownlint my_document.md --config=markdownlint-config.yml
```

```py
---
# Rule configuration goes here
MD013:
  line_length: 120
MD029:
  ol_single: true
  ul_single: true
  ol_multi: true
  ul_multi: true
  single_line_item: true
  multi_line_item: true
MD033:
  allowed_elements: ["kbd"]
  ignore: ["`", "\\", "&lt;", "&gt;", "&quot;"]
  attributes:
    kbd: ["class"]

```

**Comment by shane0** [comment]
```yml
stages:
  - lint

markdownlint:
  stage: lint
  image: alpine:latest
  before_script:
    - apk update && apk add nodejs npm
    - npm install -g markdownlint-cli
  script:
    - markdownlint docs/
```

**Comment by shane0** [comment]
# coverage and cucumber

```text
# features/file.feature

Feature: Verify file contents
    Scenario: Check if file exists and contains content that matches regex
        Given a file exists with path "test.txt"
        When I check the contents of the file
        Then the file contains content that matches the regex "Hello, world"

# steps/file_steps.py

import os
import re
import pytest
import subprocess

from behave import given, when, then

@given('a file exists with path "{file_path}"')
def step_impl(context, file_path):
    context.file_path = file_path
    assert os.path.isfile(file_path)

@when('I check the contents of the file')
def step_impl(context):
    with open(context.file_path, 'r') as f:
        context.file_contents = f.read()

@then('the file contains content that matches the regex "{regex}"')
def step_impl(context, regex):
    assert re.search(regex, context.file_contents)

# features/steps/steps.py

import subprocess

from behave import given, when, then

@given('I have installed pytest-cov')
def step_impl(context):
    try:
        subprocess.check_output(['pip', 'install', 'pytest-cov'])
    except subprocess.CalledProcessError as e:
        raise AssertionError("Failed to install pytest-cov: {}".format(e.output))

@when('I run the tests with coverage')
def step_impl(context):
    result = subprocess.run(['pytest', '--cov-report', 'html', '--cov', '.'], stdout=subprocess.PIPE)
    context.coverage_report = result.stdout.decode('utf-8')

@then('I can view the coverage report in my browser')
def step_impl(context):
    assert "Coverage report generated" in context.coverage_report
```

**Comment by shane0** [comment]
pip install behave pytest-cov

behave --no-capture --no-capture-stderr

**Comment by shane0** [comment]
# curl api pipeline

```yml
stages:
  - test

variables:
  HOST: example.com
  ENDPOINT: /api/v1/status

test:
  image: alpine
  script:
    - response=$(curl -s -o /dev/null -w "%{http_code} %{response_code}\n%{response_body}" "https://${HOST}${ENDPOINT}")
    - status=$(echo "$response" | head -n 1 | awk '{print $1}')
    - body=$(echo "$response" | tail -n +2)
    - echo "$body" | grep "expected_text"
    - if [[ $status -ne 200 ]]; then echo "Error: API returned $status"; exit 1; fi
```

**Comment by shane0** [comment]
# unzip stuff in pipelines

```py
import argparse
import zipfile

def extract_files(zip_path, files_to_extract):
    with zipfile.ZipFile(zip_path, 'r') as zip_file:
        for file_name in files_to_extract:
            zip_file.extract(file_name)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Extract files from a zip file.')
    parser.add_argument('zip_path', type=str, help='Path to the zip file.')
    parser.add_argument('files_to_extract', nargs='+', type=str, help='List of files to extract.')
    args = parser.parse_args()
    extract_files(args.zip_path, args.files_to_extract)
```

```yml
extract_files:
  script:
    - python extract_files.py /path/to/zip/file.zip file1.txt file2.txt file3.txt
  variables:
    GIT_SSL_NO_VERIFY: "true"

```

**Comment by shane0** [comment]
# output option

```py
import os

def extract_files(zip_path, files_to_extract, extract_dir='.'):
    with zipfile.ZipFile(zip_path, 'r') as zip_file:
        for file_name in files_to_extract:
            zip_file.extract(file_name, path=os.path.abspath(extract_dir))
```

```yml
extract_files:
  script:
    - cd /path/to/extract/dir
    - python /path/to/extract_files.py /path/to/zip/file.zip file1.txt file2.txt file3.txt
  variables:
    GIT_SSL_NO_VERIFY: "true"
```
