### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by shane0** [shane0/shane0.github.io#6]
```yml
version: "3"

services:
  react-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
```

**Comment by shane0** [comment]
# express

```yml
version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/myapp
    depends_on:
      - db
  db:
    image: mongo:latest
    volumes:
      - ./data:/data/db

```

**Comment by shane0** [comment]
# treafik

```yml
version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.yourdomain.com`)
      - traefik.http.routers.traefik.entrypoints=http,https
      - traefik.http.routers.traefik.middlewares=redirect-to-https@file
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt

  app:
    build: .
    container_name: app
    restart: always
    environment:
      - NODE_ENV=production
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`app.yourdomain.com`)
      - traefik.http.routers.app.entrypoints=https
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=letsencrypt
      - traefik.http.services.app.loadbalancer.server.port=3000
```

**Comment by shane0** [comment]
# treafik and a bunch of stuff

```yml
version: "3.7"

services:
  traefik:
    image: traefik:v2.5
    restart: always
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=your-email@example.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  mkdocs1:
    image: squidfunk/mkdocs-material:7.2.8
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mkdocs1.rule=Host(`mkdocs1.example.com`)"
      - "traefik.http.routers.mkdocs1.entrypoints=websecure"
      - "traefik.http.routers.mkdocs1.tls.certresolver=letsencrypt"
    volumes:
      - ./mkdocs1:/docs

  mkdocs2:
    image: squidfunk/mkdocs-material:7.2.8
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mkdocs2.rule=Host(`mkdocs2.example.com`)"
      - "traefik.http.routers.mkdocs2.entrypoints=websecure"
      - "traefik.http.routers.mkdocs2.tls.certresolver=letsencrypt"
    volumes:
      - ./mkdocs2:/docs

  wordpress:
    image: wordpress:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.example.com`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=letsencrypt"
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./mysql:/var/lib/mysql

  express:
    image: node:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.express.rule=Host(`express.example.com`)"
      - "traefik.http.routers.express.entrypoints=websecure"
      - "traefik.http.routers.express.tls.certresolver=letsencrypt"
    working_dir: /app
    volumes:
      - ./express:/app
    command: npm start
    environment:
      - NODE_ENV=production
```

**Comment by shane0** [comment]
# django


```yml
version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_DEBUG=false
      - DJANGO_SECRET_KEY=secret
      - DJANGO_ALLOWED_HOSTS=example.com,www.example.com
    volumes:
      - .:/code
    expose:
      - 8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.example.rule=Host(`example.com`) || Host(`www.example.com`)
      - traefik.http.routers.example.entrypoints=websecure
      - traefik.http.routers.example.tls=true
      - traefik.http.routers.example.tls.certresolver=le
      - traefik.http.services.example.loadbalancer.server.port=8000
    depends_on:
      - db
    networks:
      - web

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=myprojectuser
      - POSTGRES_PASSWORD=myprojectpassword
      - POSTGRES_DB=myproject
    volumes:
      - dbdata:/var/lib/postgresql/data/
    networks:
      - web

  traefik:
    image: traefik:v2.5
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.email=youremail@example.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - web

volumes:
  dbdata:

networks:
  web:
```

**Comment by shane0** [comment]
# django treafik sqlite

```yml
version: '3'

services:

  db:
    image: sqlite
    volumes:
      - db-data:/var/lib/sqlite
    networks:
      - traefik

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
    labels:
      - "traefik.http.routers.myapp.rule=Host(`myapp.example.com`)"
      - "traefik.http.services.myapp.loadbalancer.server.port=8000"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.myapp.tls=true"
      - "traefik.http.routers.myapp.tls.certresolver=lets-encrypt"
    depends_on:
      - db
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik
volumes:
  db-data:
    driver: local
```
