### ISSUE TITLE
cucumber

### ISSUE THREAD

**Issue by shane0** [shane0/shane0.github.io#8]
# check web

```gherkin
Feature: Web Scraper

  Scenario Outline: Scrape a Webpage for Content
    Given I navigate to "<url>"
    When I scrape the webpage for "<regex>"
    Then I should see the following data table:
      | Matched Content |
      | <expected>      |

    Examples:
      | url                               | regex                                | expected                                    |
      | https://en.wikipedia.org/wiki/Python_(programming_language) | Programming languages written in Python | Python, CPython, Jython, IronPython, Stackless |
```

```py
from behave import given, when, then
import requests
import re

@given('I navigate to "{url}"')
def navigate_to_url(context, url):
    context.response = requests.get(url)

@when('I scrape the webpage for "{regex}"')
def scrape_webpage(context, regex):
    pattern = re.compile(regex, re.IGNORECASE)
    matches = pattern.findall(context.response.text)
    context.scraped_data = matches

@then('I should see the following data table:')
def assert_data_table(context):
    expected_data = [row['Matched Content'] for row in context.table]
    assert context.scraped_data == expected_data, f"Expected {expected_data}, but got {context.scraped_data}"
```

**Comment by shane0** [comment]
# mock web

```gherkin
Feature: Scraping a website

  Scenario: Scraping a website for data
    Given I have a mock server running on "http://localhost:8000"
    And I have the following data table:
      | Column 1 | Column 2 | Column 3 |
      | value 1  | value 2  | value 3  |
    When I scrape the website "http://localhost:8000/data"
    Then I should see the following values in the response:
      | Column 1 | Column 2 | Column 3 |
      | value 1  | value 2  | value 3  |
```

```py
import responses

@responses.activate
def test_scraping_website(context):
    # Set up the mock response
    responses.add(responses.GET, 'http://localhost:8000/data',
                  json=[{"Column 1": "value 1", "Column 2": "value 2", "Column 3": "value 3"}])

    # Run the test
    context.runner.invoke(scrape_website, ['http://localhost:8000/data'])

    # Assert that the response contains the expected values
    assert context.response == [{"Column 1": "value 1", "Column 2": "value 2", "Column 3": "value 3"}]
```

**Comment by shane0** [comment]
# mock mock mock


```gherkin
Feature: Mock website

  Scenario: Verify homepage content
    Given the mock web server is running
    When a user visits the homepage
    Then the homepage should contain "Welcome to the mock website"

```

```py
from behave import given, when, then, after
import requests
import subprocess
import re

MOCK_SERVER_PORT = 8000

@given("the mock web server is running")
def start_mock_server(context):
    context.mock_server_process = subprocess.Popen(["python", "mock_server.py"])
    context.mock_server_url = f"http://localhost:{MOCK_SERVER_PORT}"

@when("a user visits the homepage")
def visit_homepage(context):
    context.response = requests.get(context.mock_server_url)

@then("the homepage should contain {text}")
def verify_homepage_content(context, text):
    assert re.search(text, context.response.text)

@after
def stop_mock_server(context):
    context.mock_server_process.terminate()
```

```py
from flask import Flask

app = Flask(__name__)

@app.route('/')
def index():
    return '<html><body><h1>Welcome to the mock website</h1></body></html>'

if __name__ == '__main__':
    app.run(port=8000)

```

**Comment by shane0** [comment]
# allow fail

```yml
stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building..."

test:
  stage: test
  script:
    - echo "Running tests..."
    - exit 1  # simulate test failure
  allow_failure: true  # allow this job to fail

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
  dependencies:
    - build
    - test
```

**Comment by shane0** [comment]
# break stage dependancy

```yml
stages:
  - build
  - test
  - deploy

build:
  script:
    - echo "Building..."
  stage: build

test:
  script:
    - echo "Testing..."
  stage: test
  needs: []

deploy:
  script:
    - echo "Deploying..."
  stage: deploy
  needs: []
```
